import { TouristLayout } from '@/components/tourist/tourist-layout';
import { Head, Link, router } from '@inertiajs/react';
import { Bell, CalendarDays, CheckCheck, CreditCard, Package, ShieldCheck } from 'lucide-react';

type Item = { id: string; data: { activity_type: string; title: string; message: string; reference: string; url: string }; is_read: boolean; created_at: string; created_at_exact?: string };
type Props = { notifications: { data: Item[]; links: { url: string | null; label: string; active: boolean }[]; total: number } };

export default function NotificationIndex({ notifications }: Props) {
    const open = (item: Item) => item.is_read ? router.visit(item.data.url) : router.patch(route('tourist.notifications.read', item.id), {}, { onSuccess: () => router.visit(item.data.url) });
    return <TouristLayout><Head title="Notifications" /><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-600">Tourist account</p><h1 className="text-3xl font-extrabold">Notifications</h1><p className="mt-1 text-slate-500">Reservation, payment, order, and verification updates.</p></div><button onClick={() => router.patch(route('tourist.notifications.read-all'))} className="inline-flex items-center justify-center gap-2 rounded-xl border border-teal-700 px-4 py-2.5 text-sm font-bold text-teal-700"><CheckCheck className="size-4" /> Mark all as read</button></div><div className="mt-6 overflow-hidden rounded-2xl border border-orange-100 bg-white shadow-sm">{notifications.data.map(item => { const Icon = item.data.activity_type === 'product_order' ? Package : item.data.activity_type === 'verification' ? ShieldCheck : item.data.activity_type === 'payment' ? CreditCard : CalendarDays; return <button key={item.id} onClick={() => open(item)} className={`flex w-full items-start gap-4 border-b p-5 text-left last:border-0 hover:bg-orange-50/50 ${item.is_read ? 'bg-white' : 'bg-orange-50'}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white text-orange-600 shadow-sm"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-3"><strong className="text-slate-900">{item.data.title}</strong>{!item.is_read && <span className="mt-1 size-2.5 shrink-0 rounded-full bg-orange-600" />}</span><span className="mt-1 block text-sm leading-6 text-slate-600">{item.data.message}</span><span className="mt-2 block text-xs font-semibold text-teal-700">{item.data.reference} · {item.created_at}</span></span></button>; })}{notifications.data.length === 0 && <div className="grid place-items-center gap-3 px-5 py-16 text-center"><Bell className="size-10 text-slate-300" /><p className="font-bold text-slate-700">No notifications yet</p><p className="text-sm text-slate-500">Important account updates will appear here.</p></div>}<div className="flex flex-wrap gap-1 border-t p-4">{notifications.links.map((link, index) => link.url ? <Link key={index} href={link.url} className={`rounded-lg px-3 py-1.5 text-sm ${link.active ? 'bg-teal-700 text-white' : 'border'}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : null)}</div></div></TouristLayout>;
}
