import AdminLayout from '@/layouts/admin-layout';
import { Head, Link, router } from '@inertiajs/react';
import { Mail, MapPin, Phone, ShieldCheck, UserRound } from 'lucide-react';

type Reservation = { id: number; reservation_number: string; total_amount: string; status: string; created_at: string; enterprise?: { business_name: string }; items: { check_in?: string; check_out?: string; reservation_date?: string; service?: { name: string } }[] };
type Verification = { id: number; id_type: string; verification_status: string; rejection_reason?: string; submitted_at?: string } | null;
type Props = { canManageStatus: boolean; tourist: { id: number; name: string; email: string; phone?: string; country?: string; province?: string; city_municipality?: string; status: string; email_verified_at?: string; created_at: string; verification: Verification }; reservationSummary: Record<string, string | number>; reservations: { data: Reservation[]; links: { url: string | null; label: string; active: boolean }[] } };
const readable = (value?: string) => (value || 'not_submitted').replaceAll('_', ' ');
const money = (value: string | number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(Number(value));

export default function TouristShow({ canManageStatus, tourist, reservationSummary, reservations }: Props) {
    const location = [tourist.city_municipality, tourist.province, tourist.country].filter(Boolean).join(', ') || 'Not provided';
    const setStatus = (status: string) => window.confirm(`Change this account to ${status}?`) && router.patch(`/admin/tourists/${tourist.id}/status`, { status }, { preserveScroll: true });
    const details = [[Mail, 'Email', tourist.email, tourist.email_verified_at ? 'Verified' : 'Unverified'], [Phone, 'Mobile number', tourist.phone || 'Not provided', ''], [MapPin, 'Location', location, ''], [ShieldCheck, 'Identity status', readable(tourist.verification?.verification_status), tourist.verification?.id_type || 'No documents submitted']] as const;
    const metrics = [['Total', reservationSummary.total], ['Pending', reservationSummary.pending], ['Confirmed', reservationSummary.confirmed], ['Completed', reservationSummary.completed], ['Confirmed value', money(reservationSummary.total_spent)]];

    return <AdminLayout title="Tourist Account" breadcrumbs={[{ title: 'Dashboard', href: '/dashboard' }, { title: 'Tourists', href: '/admin/tourists' }, { title: tourist.name, href: `/admin/tourists/${tourist.id}` }]}>
        <Head title={tourist.name} />
        <header className="flex flex-col gap-4 rounded-3xl bg-teal-800 p-7 text-white sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-white/15"><UserRound className="size-8" /></span><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Tourist account</p><h1 className="text-3xl font-extrabold">{tourist.name}</h1><p className="text-teal-50">Member since {new Date(tourist.created_at).toLocaleDateString()}</p></div></div><span className={`w-fit rounded-full px-4 py-2 text-sm font-bold capitalize ${tourist.status === 'active' ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-700'}`}>{tourist.status}</span></header>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_340px]"><main className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Profile information</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{details.map(([Icon, title, value, note]) => <div key={title} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-orange-50 text-orange-600"><Icon className="size-5" /></span><div><p className="text-xs font-bold uppercase text-slate-400">{title}</p><p className="font-semibold text-slate-800">{value}</p>{note && <p className="text-xs text-slate-500">{note}</p>}</div></div>)}</div></section>
            <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Reservation history</h2><p className="text-sm text-slate-500">Bookings linked to this registered account.</p><div className="mt-5 grid gap-3 sm:grid-cols-5">{metrics.map(([title, value]) => <div key={title} className="rounded-xl bg-slate-50 p-3"><strong className="block text-lg">{value}</strong><span className="text-xs text-slate-500">{title}</span></div>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Reservation</th><th>Enterprise / Service</th><th>Schedule</th><th>Amount</th><th>Status</th></tr></thead><tbody>{reservations.data.map(reservation => { const item = reservation.items[0]; return <tr key={reservation.id} className="border-b"><td className="p-3 font-bold">{reservation.reservation_number}</td><td>{reservation.enterprise?.business_name || 'Enterprise'}<small className="block text-slate-500">{item?.service?.name || 'Service unavailable'}</small></td><td>{item?.check_in && item?.check_out ? `${item.check_in} – ${item.check_out}` : item?.reservation_date || new Date(reservation.created_at).toLocaleDateString()}</td><td className="font-semibold">{money(reservation.total_amount)}</td><td className="capitalize">{readable(reservation.status)}</td></tr>; })}</tbody></table>{reservations.data.length === 0 && <p className="py-8 text-center text-slate-500">No linked reservations yet.</p>}</div><div className="mt-4 flex gap-1">{reservations.links.map((link, index) => link.url ? <Link key={index} href={link.url} preserveScroll className={`rounded-lg px-3 py-1.5 text-sm ${link.active ? 'bg-teal-700 text-white' : 'border'}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : null)}</div></section></main>
            <aside className="space-y-5"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-extrabold"><ShieldCheck className="size-5 text-teal-700" /> Identity verification</h2><p className="mt-4 capitalize">Status: <strong>{readable(tourist.verification?.verification_status)}</strong></p>{tourist.verification?.submitted_at && <p className="text-sm text-slate-500">Submitted {new Date(tourist.verification.submitted_at).toLocaleDateString()}</p>}{tourist.verification?.rejection_reason && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{tourist.verification.rejection_reason}</p>}{tourist.verification ? <Link href={`/admin/tourist-verifications/${tourist.verification.id}`} className="mt-4 block rounded-xl border border-teal-700 px-4 py-2.5 text-center font-bold text-teal-700">Open verification request</Link> : <p className="mt-3 text-sm text-slate-500">No identity documents submitted.</p>}</section>
            {canManageStatus && <section className="rounded-2xl border border-orange-100 bg-orange-50 p-6"><h2 className="text-lg font-extrabold">Account controls</h2><p className="mt-1 text-sm text-slate-600">Suspension signs out active sessions and prevents login.</p>{tourist.status === 'active' ? <button onClick={() => setStatus('suspended')} className="mt-4 w-full rounded-xl bg-red-700 px-4 py-2.5 font-bold text-white">Suspend account</button> : <button onClick={() => setStatus('active')} className="mt-4 w-full rounded-xl bg-emerald-700 px-4 py-2.5 font-bold text-white">Reactivate account</button>}</section>}</aside></div>
    </AdminLayout>;
}
